server:
  port: 18002
# 数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:10.0.11.119}:${MYSQL_PORT:3306}/main-data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: eissys
      password: 'Qifeng@)!(2019'
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select now() from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
      # 监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: "000000"
  redis:
      database: 0
      host: ${REDIS_HOST:10.0.11.122}
      port: ${REDIS_PORT:6379}
      cluster:
        nodes:
          - 10.0.11.122:6379
          - 10.0.11.123:6379
          - 10.0.11.124:6379
          - 10.0.11.125:6379
          - 10.0.11.126:6379
          - 10.0.11.127:6379
  rabbitmq:
    host: 10.0.11.125
    port: 5672
    username: rabbitmq
    password: 'rabbitmq'
    virtual-host: vhost
# 权限配置
security:
  ignored: |
    /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,
    /hystrix.stream/**,/info,/error,/health,/env,/metrics,/trace,/dump,
    /jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers,
    /user/name/**,/user/phone/**,/role/user/**,/menu/user/*,/client/all
  oauth2:
    resource:
      jwt:
        key-uri: http://${AUTH_CENTER_HOST:localhost}:${AUTH_CENTER_PORT:18001}/auth/oauth/token_key
      id: ${spring.application.name}
      serviceId: ${spring.application.name}
# mybatis 配置
mybatis:
  type-aliases-package: com.firstflag.main.api.mapper.model
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  file: logs/main-data.log