server:
  port: 18003
spring:
  rabbitmq:
    host: 10.0.11.125
    port: 5672
    username: rabbitmq
    password: 'rabbitmq'
    virtual-host: vhost
  boot:
      admin:
        turbine:
          location: monitor
        routes:
          endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
        discovery:
          ignored-services: consul
turbine:
    app-config: api-gateway #收集监控信息的服务名
    combine-host-port: true
    cluster-name-expression: new String('default') #集群名称
receiver:
  mobiles:
    - 13642627626
  emails: |
    shuaiqing.li@firstflag.com.cn

logging:
  file: logs/monitor.log