server:
  port: 18005
# 数据源配置
spring:
  # datasoure默认使用JDBC
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: eissys
    password: 'Qifeng@)!(2019'
    url: jdbc:mysql://${MYSQL_HOST:10.0.11.119}:${MYSQL_PORT:3306}/zipkin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  sleuth:
    enabled: false
  rabbitmq:
    host: 10.0.11.125
    port: 5672
    username: rabbitmq
    password: 'rabbitmq'
    virtual-host: vhost

zipkin:
  storage:
    type: mysql

logging:
  file: logs/zipkin-db.log